#!/usr/bin/env bash
# WS7 (issue #22) outside-in cross-implementation signature harness.
#
# Signs a pack release index with Node's built-in Ed25519 (an INDEPENDENT
# implementation), then verifies + pulls it with the Rust `kgpacks pack pull`,
# asserting every branch of the fail-closed signature policy end to end through
# the real command surface. Prints PULL_SIGNATURE_OK on full agreement; any
# divergence exits non-zero.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

ORACLE="$ROOT/qa/pull-signature/sign_oracle.mjs"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Build the CLI once, then invoke the COMPILED BINARY directly for each of the
# many checks below. Using the built binary (rather than `cargo run` per call)
# makes each invocation a fast, deterministic exec instead of a cargo freshness
# re-check + relink, keeping the whole harness well within the gadugi-test
# per-command timeout.
cargo build -q -p kgpacks-cli
TARGET_DIR="$(cargo metadata --format-version 1 \
  | python3 -c 'import json,sys; print(json.load(sys.stdin)["target_directory"])')"
KG="$TARGET_DIR/debug/kgpacks"

kg() { "$KG" "$@"; }
fail() {
  echo "PULL_SIGNATURE_DIVERGENCE: $1" >&2
  exit 1
}
# setup <dir> -> writes a Node-signed index+sidecar into <dir>, echoes pubkey.
setup() {
  mkdir -p "$1"
  node "$ORACLE" "$1" acme
}
# expect_fail <label> <cmd...> — the command MUST exit non-zero.
expect_fail() {
  local label="$1"
  shift
  if "$@" >/dev/null 2>&1; then
    fail "$label: expected failure but the pull succeeded"
  fi
}

# 1) Valid Node signature verifies under the Rust verifier (interop).
D="$TMP/valid"
PUB="$(setup "$D")"
out="$(kg --packs-dir "$D" pack pull acme --trusted-key "$PUB")" || fail "valid pull errored"
echo "$out" | grep -q '"verified": true' || fail "valid signature not verified"
echo "$out" | grep -q '"policy": "verify"' || fail "valid policy was not verify"

# 2) A signature from an untrusted key is rejected (fail-closed).
D="$TMP/wrongkey"
setup "$D" >/dev/null
WRONG="$(setup "$TMP/wrongkey_ref")" # a DIFFERENT keypair
expect_fail "untrusted-key" kg --packs-dir "$D" pack pull acme --trusted-key "$WRONG"

# 3) Tampering with the index after signing is detected.
D="$TMP/tamper"
PUB="$(setup "$D")"
node -e 'const fs=require("fs");const p=process.argv[1];fs.writeFileSync(p,fs.readFileSync(p).toString().replace("42","999"))' \
  "$D/acme.pack-release.json"
expect_fail "tamper" kg --packs-dir "$D" pack pull acme --trusted-key "$PUB"

# 4) An unsigned index is allowed (integrity-only warn) without --require-signature.
D="$TMP/unsigned"
PUB="$(setup "$D")"
rm -f "$D/acme.pack-release.json.sig"
out="$(kg --packs-dir "$D" pack pull acme --trusted-key "$PUB")" || fail "unsigned warn pull errored"
echo "$out" | grep -q '"policy": "warn"' || fail "unsigned policy was not warn"
echo "$out" | grep -q '"present": false' || fail "unsigned should report present=false"

# 5) --require-signature rejects the same unsigned index.
expect_fail "require-unsigned" kg --packs-dir "$D" pack pull acme --require-signature --trusted-key "$PUB"

# 6) --no-verify skips verification even for the unsigned index.
out="$(kg --packs-dir "$D" pack pull acme --no-verify)" || fail "no-verify pull errored"
echo "$out" | grep -q '"policy": "skip"' || fail "no-verify policy was not skip"

# 7) --require-signature together with --no-verify is a usage error.
expect_fail "mutually-exclusive" kg --packs-dir "$D" pack pull acme --require-signature --no-verify

# 8) The committed DEFAULT trusted key rejects a foreign (Node) signature.
D="$TMP/defaultkey"
setup "$D" >/dev/null
expect_fail "default-key-foreign-sig" kg --packs-dir "$D" pack pull acme

# 9) Rust-side signing round-trip (the PRODUCING half of WS7): `pack sign`
#    writes a sidecar that `pack pull --require-signature` accepts. The keypair
#    is generated by Node's independent Ed25519, so this ALSO proves a
#    Node-produced 32-byte seed loads into the Rust signer (interop both ways).
D="$TMP/rustsign"
mkdir -p "$D"
keys="$(node -e '
  const { generateKeyPairSync } = require("node:crypto");
  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  const d = Buffer.from(privateKey.export({ format: "jwk" }).d, "base64url");
  const x = Buffer.from(publicKey.export({ format: "jwk" }).x, "base64url");
  process.stdout.write(d.toString("base64") + " " + x.toString("base64"));
')" || fail "rust-sign keygen failed"
seed="${keys%% *}"
pub="${keys##* }"
# A schema-agnostic index — `pack sign` signs the RAW bytes, so any JSON works.
printf '%s' '{"name":"acme","format":"tar.gz-multipart-v1","version":"2025.6.0","total_bytes":42}' \
  >"$D/acme.pack-release.json"
printf '%s' "$seed" >"$D/seed.b64"
signed="$(kg --packs-dir "$D" pack sign acme --key-file "$D/seed.b64" --trusted-key "$pub")" \
  || fail "rust sign errored"
echo "$signed" | grep -q '"matches_trusted_key": true' || fail "rust sign did not match its own trusted key"
test -f "$D/acme.pack-release.json.sig" || fail "rust sign wrote no sidecar"
out="$(kg --packs-dir "$D" pack pull acme --require-signature --trusted-key "$pub")" \
  || fail "rust sign->pull round-trip errored"
echo "$out" | grep -q '"verified": true' || fail "rust-produced signature did not verify"
echo "$out" | grep -q '"policy": "verify"' || fail "rust round-trip policy was not verify"

# 10) `pack sign` with no key source is a usage error (never signs implicitly).
unset KGPACKS_RELEASE_SIGNING_KEY
expect_fail "sign-no-key" kg --packs-dir "$D" pack sign acme

echo "PULL_SIGNATURE_OK"
