#!/usr/bin/env bash
# Cross-implementation chunker parity check (qa-team / gadugi-agentic-test).
#
# Proves the Rust chunker (`kgpacks-embeddings::chunker`) produces byte-for-byte
# identical chunk ids and contents to the canonical `agent-kgpacks-ts`
# `windowText` reference, on a shared corpus that exercises multi-window
# overlap, short text, multibyte (Cyrillic), BOM/NEL trim parity, and interior
# whitespace preservation.
#
# 1. Runs the Rust `chunk_dump` example over the shared corpus.
# 2. Diffs its output against the committed golden `expected.tsv` (generated by
#    the real TS oracle).
# 3. When `node` is available, additionally regenerates the golden live from the
#    TS reference oracle and asserts it still matches — a true side-by-side
#    Rust-vs-TS comparison, not just a snapshot.
#
# Prints `CHUNKER_PARITY_OK` and exits 0 on success; prints the diff and exits 1
# on any divergence.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"
CORPUS="$HERE/corpus.tsv"
EXPECTED="$HERE/expected.tsv"
ORACLE="$HERE/reference_oracle.mjs"
SIZE=20
OVERLAP=5

cd "$REPO_ROOT"

ACTUAL="$(mktemp)"
trap 'rm -f "$ACTUAL" "${LIVE:-}"' EXIT

# 1 + 2: Rust chunker vs committed golden.
cargo run -q --example chunk_dump -p kgpacks-embeddings --locked -- \
  "$CORPUS" "$SIZE" "$OVERLAP" > "$ACTUAL"

if ! diff -u "$EXPECTED" "$ACTUAL"; then
  echo "CHUNKER_PARITY_FAILED: Rust output diverged from the golden (agent-kgpacks-ts) fixture"
  exit 1
fi

# 3: Optional live cross-check against the real TS reference oracle.
if command -v node >/dev/null 2>&1; then
  LIVE="$(mktemp)"
  node "$ORACLE" "$CORPUS" "$SIZE" "$OVERLAP" > "$LIVE"
  if ! diff -u "$LIVE" "$ACTUAL"; then
    echo "CHUNKER_PARITY_FAILED: Rust output diverged from the live TS reference oracle"
    exit 1
  fi
  echo "checked Rust == committed golden == live agent-kgpacks-ts oracle"
else
  echo "checked Rust == committed golden (node unavailable; skipped live TS oracle)"
fi

echo "CHUNKER_PARITY_OK"
